### ISSUE TITLE
[Feature request] Could you please add tests?

### ISSUE THREAD

**Issue by ternaus** [talkpython/web-applications-with-fastapi-course#1]
It would be nice to see how various parts of the code could be tested.

**Comment by mikeckennedy** [comment]
Hi @ternaus Thanks for the idea. We are actually planning a follow up course on testing, documenting APIs, and a bunch of other such goodies. This course is meant to be more of a getting started with FastAPI than fully comprehensive. :)

EDIT: Actually, I see this is on the upcoming course. Sorry! But the comment still applies.

**Comment by ruslaniv** [comment]
@mikeckennedy 
Hi Michael! 
Any news on 
> a follow up course on testing, documenting APIs, and a bunch of other such goodies.

**Comment by mikeckennedy** [comment]
Hi Ruslaniv,

We are working on a couple of follow on courses. One specifically about auth and another on the network engineering side of things. This one I mentioned above is still on the roadmap but not yet under development.
