### ISSUE TITLE
aiofiles not needed as a requirement

### ISSUE THREAD

**Issue by possnfiffer** [talkpython/web-applications-with-fastapi-course#12]
In Chapter 4, Static files, you show a `ModuleNotFoundError: No module named 'aiofiles'` error when mounting static files with `app.mount('/static', StaticFiles(directory='static'), name='static')`

I'm not getting that error and when I run `pip list` I'm not seeing aiofiles listed. Do you think Starlette updated StaticFiles to use something else?

**Comment by possnfiffer** [comment]
or was that something to do with installing fastapi-chameleon from pip vs installing it from github? You do mention a dependency between aiofiles and chameleon

**Comment by possnfiffer** [comment]
although I just tried to import aiofiles and didn't get anything

```
Python 3.10.1 (main, Feb  3 2022, 11:17:21) [Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3 on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiofiles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aiofiles'
```

**Comment by mikeckennedy** [comment]
Hey Roller. It does look like that dependency is gone (and good thing). I guess starlette took it out but I couldn't find a record of that in the history (didn't dive too deep though). Here's what I have installed for the near final version of the course.

<img width="836" alt="Screen Shot 2022-02-25 at 11 02 04 AM" src="https://user-images.githubusercontent.com/2035561/155772941-35e72727-559f-450c-bf5c-a890a2211b1d.png">
