### ISSUE TITLE
Basic App Output

### ISSUE THREAD

**Issue by gloc-mike** [talkpython/web-applications-with-fastapi-course#2]
Hi Mike,

Not sure why but the output I'm getting from the basic app does not display the JSON, Raw Data, etc. fastAPI tabs at the top of the browser window like your example shows.

Do you know why that might be?

Mine:
![Screen Shot 2021-03-10 at 21 17 31](https://user-images.githubusercontent.com/2324626/110614158-28afc080-81e6-11eb-834e-708fcd18059a.png)

Yours:
![Screen Shot 2021-03-10 at 21 16 43](https://user-images.githubusercontent.com/2324626/110614211-39603680-81e6-11eb-8d1a-92e37d83426c.png)

Thanks
Michael

**Comment by mikeckennedy** [comment]
Hi @gloc-mike That is odd. I don't know why you're seeing that. I'd guess the web method looks like:

```
def index():
   return "Hello world"
```

The one I have is:

```
def index():
   return {"message": "Hello world"}
```

If that's not it, perhaps it's formatting in your browser? Do a view source also I guess to be sure. Let me know what you find.

**Comment by gloc-mike** [comment]
Hi @mikeckennedy,

Thanks for the response. I tried both but neither altered the browser look.

I thought it might be browser specific so I tried Opera, Safari and re-downloaded Chrome but all produce the same result.

In Opera, I found this error:
![Screen Shot 2021-03-11 at 09 52 12](https://user-images.githubusercontent.com/2324626/110708933-8c220880-824f-11eb-9b53-8504933f2302.png)

But I don't see that error in Safari nor in Chrome so probably Opera specific. There are no exceptions anywhere else in any of the browsers that I can find.

Any other thoughts?

**Comment by gloc-mike** [comment]
Hi @mikeckennedy,

I pushed my program files to GitHub. I know it's simple but I might have some domestic blindness and have missed something really obvious.

https://github.com/gloc-mike/Faux-PyPI

**Comment by mikeckennedy** [comment]
Thanks. I ran your version in github. Here's what I get with it *exactly* as is which is `return "hello world"` and the output is the same as you have:

<img width="145" alt="Screen Shot 2021-03-10 at 9 03 44 PM" src="https://user-images.githubusercontent.com/2035561/110738461-306e6580-81e4-11eb-9445-65d05f1c52f7.png">


But running this version:

```
@app.get('/')
def index():
    return {
        'message': "Hello World"
    }
```

Gets me:

<img width="196" alt="Screen Shot 2021-03-10 at 9 04 01 PM" src="https://user-images.githubusercontent.com/2035561/110738457-2d737500-81e4-11eb-8a65-31e1331621bc.png">

I think what you might be seeing is you must restart the web app, not just change and save the python file to see any difference.

**Comment by gloc-mike** [comment]
Hi @mikeckennedy,

Yes, I alway restart the server after making changes. It doesn't make any difference which version of the return statement I use, I still do not get the "JSON Raw Data Headers" FastAPI buttons displayed in the browser.

I looked through the FastAPI issues but could not find anything related to this.

**Comment by mikeckennedy** [comment]
Oh, I misunderstood the part you're looking for. You have to use a browser with that display. The reason I have that is because I use Firefox. I wouldn't get that on brave/chrome/safari/etc.

**Comment by gloc-mike** [comment]
Oh sorry @mikeckennedy ! My bad. I shouldn't have mixed the output screenshots like that. 

We got there in the end! :) Thanks! Firefox all the way! Yay! :)

**Comment by mikeckennedy** [comment]
Glad you got it figured out. Yes, the mixed browser content threw me off. :)
