### ISSUE TITLE
Error in engine.py, using python3.9 (posixpath.py) when template_path is None

### ISSUE THREAD

**Issue by Cristianasp** [talkpython/web-applications-with-fastapi-course#3]
Hello, got this error trying to run using ch5-viewmodels from TalkPython Course... template_path is None.

I believe the problem is that `fastapi_chameleon.global_init()` is called after `from fastapi_chameleon import template` in home.py

```
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
expected str, bytes or os.PathLike object, not NoneType
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/site-packages/fastapi_chameleon/engine.py", line 72, in response_inner
    if not os.path.exists(os.path.join(template_path, template_file)):
  File "/home/cristiana/AAA-wip/Cursos-Programming/Curso-TalkPython-FastAPI-FullWeb/web-applications-with-fastapi-cris/views/home.py", line 13, in <module>
    def index(request: Request):
  File "/home/cristiana/AAA-wip/Cursos-Programming/Curso-TalkPython-FastAPI-FullWeb/web-applications-with-fastapi-cris/main.py", line 7, in <module>
    from views import home
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

**Comment by prcutler** [comment]
This looks really similar to the error I'm getting and I'm going to talk to Michael in office hours today in about 30 minutes.

This line in particular matches an error I'm getting:
`  File "/home/cristiana/anaconda3/envs/fastapi/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)`

I also see:

```
File "/Users/prcutler/workspace/silversaucer/testvenv/lib/python3.9/site-packages/fastapi_chameleon/engine.py", line 71, in response_inner
    if not os.path.exists(os.path.join(template_path, template_file)):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
```

I have a bug open in my repo at https://github.com/prcutler/silversaucer/issues/317 and if I find an answer, I'll post here as well.

**Comment by Cristianasp** [comment]
Hello @prcutler , the error seams to be in engine.py (fastapi-chameleon). It is calling  `os.path.join` with a parameter with None (template_path).

I have made a temporary solution in the following function, to be able to run the code.

Yet, I havent figured out where template_path should be declared in order to make this works ;-)

```
    def response_inner(f):
        nonlocal template_file

        if not template_file:
            # Use the default naming scheme: template_folder/module_name/function_name.pt
            module = f.__module__
            if '.' in module:
                module = module.split('.')[-1]
            view = f.__name__
            template_file = f'{module}/{view}.html'

            if template_path is not None:
                if not os.path.exists(os.path.join(template_path, template_file)):
                    template_file = f'{module}/{view}.pt'
            else:
                template_file = f'{module}/{view}.pt'
```

**Comment by andreaslongo** [comment]
A quick workaround would be to call `global_init()` before any `views` import.

From `./code/ch8-async-databases/main.py`:
```python
from pathlib import Path

import fastapi
import fastapi_chameleon
import uvicorn
from starlette.staticfiles import StaticFiles

from data import db_session

fastapi_chameleon.global_init('templates', auto_reload=True)

from views import account
from views import home
from views import packages
```

Note the `auto_reload=True` argument which set to `dev_mode` variable in the origin call.

**Comment by prcutler** [comment]
This should be fixed as Michael released a new version.

Just run:

`pip install git+https://github.com/mikeckennedy/fastapi-chameleon` again

**Comment by Cristianasp** [comment]
> This should be fixed as Michael released a new version.
> 
> Just run:
> 
> `pip install git+https://github.com/mikeckennedy/fastapi-chameleon` again

I believe not, since I installed the package today.

**Comment by prcutler** [comment]
He released a new version after these bug reports and it did fix it for me.  Make sure you're using fastapi_chameleon-0.1.7 and not 0.1.6

See:  https://github.com/mikeckennedy/fastapi-chameleon/issues/7

**Comment by andreaslongo** [comment]
`fastapi-chameleon-0.1.7` fixed it for me too.

Thanks @prcutler and @mikeckennedy

**Comment by mikeckennedy** [comment]
Glad you all got it working. Sorry for the trouble.

**Comment by Cristianasp** [comment]
Cool ! Thank you !
