### ISSUE TITLE
Modifying .pt files and having Uvicorn reload

### ISSUE THREAD

**Issue by mattduffield** [talkpython/web-applications-with-fastapi-course#6]
Hi Michael, 

Great presentation! I was wondering if it is possible to have Uvicorn reload when you make changes to the templates just like it does when you make changes to the .py files?

Thanks in advanced!

**Comment by mattduffield** [comment]
Michael,

I am a little disappointed that you offer these courses and encourage people to ask questions. However, you seem to ignore our questions. Any response is better than simply ignoring it, especially for a paid course.

**Comment by MichaPau** [comment]
Have you tried: `fastapi_chameleon.global_init('templates', auto_reload='True')`
It works for me...
The source files from the repository have it actually declared in main.py with a dev_mode flag which is set to `true`

I mean it doesn't restart uvicorn but it updates a new response with the changes in the template

**Comment by mattduffield** [comment]
Great! Does that mean in the bottom of the main.py file, it would look like the following:

```python
if __name__ == '__main__':
    main()
else:
    configure(dev_mode=True)
```

And at the top somewhere, I would have the line:

```python
fastapi_chameleon.global_init('templates', auto_reload='True')
```

**Comment by mikeckennedy** [comment]
Hi @mattduffield and @MichaPau 

Micha, thanks for pointing out the `auto_reload` feature there. That's exactly right. It should be just passing that through to the template engine IIRC.

Matt, sorry for the slow reply. I lost track of this issue in the repo. But for some reason it got cleared out of my inbox. Sorry you felt ignored. FWIW, we have almost 40 repos, each with their own traffic and conversations and it's hard to keep on top of all of them all the time. Not to mention my inbox is a complete mess before that.

I think this solves it, but feel free to reopen if not.

**Comment by mikeckennedy** [comment]
BTW, you do NOT want to have this reload feature in production. It makes every requests slower and you want all the caching you can get. Just restart the worker process for that. But in dev, this should do it. So that would mean:

```python
if __name__ == '__main__':
    main()
else:
    configure(dev_mode=False)
```

Is probably what you want. And pass dev_mode=True somewhere inside `main()`.
