### ISSUE TITLE
Using of deprecated method relation()

### ISSUE THREAD

**Issue by zakharov-dmitry** [talkpython/web-applications-with-fastapi-course#8]
Hi Michael,

first of all thank for perfect course!=)
One question, is there any reasons for using of the method orm.relation() instead of the synonym orm.relationship() in data/package.py line 29?
According to the SQLAlchemy docs it is already deprecated since v.1.4.

Many thanks!

https://github.com/talkpython/web-applications-with-fastapi-course/blob/f197a394085547ed4a4367bc617de5c6e3c3830d/code/ch8-async-databases/data/package.py#L29

**Comment by mikeckennedy** [comment]
Hi @zakharov-dmitry Thanks! No reason at all. Probably I just typed relationship and PyCharm autocompleted it. Or I was just following autocomplete myself and landed there. I think we were using 1.3 on chapter 7 then upgraded to 1.4 for chapter 8 and just carried it forward so missed the deprecation warning.

I'll go back and update the code soon (feel free to bug me if I don't ;) )

**Comment by zakharov-dmitry** [comment]
Ok, thanks for the explanation!=)

**Comment by mikeckennedy** [comment]
Thanks. I updated the code accordingly: 

https://github.com/talkpython/web-applications-with-fastapi-course/commit/4c79dfc20e75cc5fce88734a5e5f99c9f96e901d
